export const FETCH_AGENT_SUCCESS = "FETCH_AGENT_SUCCESS";
export const FETCH_AGENT_FAILURE = "FETCH_AGENT_FAILURE";
export const AUTH_USER = "AUTH_USER";

//*************************
export const FETCH_ANNONCEMENT_SUCCESS = "FETCH_ANNONCEMENT_SUCCESS";
export const FETCH_ANNONCEMENT_FAILURE = "FETCH_ANNONCEMENT_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";

export const FETCH_SELECTED_ANNONCEMENT_SUCCESS =
  "FETCH_SELECTED_ANNONCEMENT_SUCCESS";
export const FETCH_SELECTED_ANNONCEMENT_FAILED =
  "FETCH_SELECTED_ANNONCEMENT_FAILED";

export const FETCH_MY_ANNONCEMENTS_LIST_SUCCESS =
  "FETCH_MY_ANNONCEMENTS_LIST_SUCCESS";
export const FETCH_MY_ANNONCEMENTS_LIST_FAILURE =
  "FETCH_MY_ANNONCEMENTS_LIST_FAILURE";

export const DELETE_ANNONCEMENT_SUCCESS = "DELETE_ANNONCEMENT_SUCCESS";
export const DELETE_ANNONCEMENT_FAILURE = "DELETE_ANNONCEMENT_FAILURE";

export const FETCH_SELECTED_ANNONCEMENT_TO_EDIT_SUCCESS =
  "FETCH_SELECTED_ANNONCEMENT_TO_EDIT_SUCCESS";
export const FETCH_SELECTED_ANNONCEMENT_TO_EDIT_FAILED =
  "FETCH_SELECTED_ANNONCEMENT_TO_EDIT_FAILED";

export const EDIT_SELECTED_ANNONCEMENT_SUCCESS =
  "EDIT_SELECTED_ANNONCEMENT_SUCCESS";
export const EDIT_SELECTED_ANNONCEMENT_FAILED =
  "EDIT_SELECTED_ANNONCEMENT_FAILED";

export const FETCH_MY_FAVORITES_ANNONCEMENTS_LIST_SUCCESS =
  "FETCH_MY_FAVORITES_ANNONCEMENTS_LIST_SUCCESS";
export const FETCH_MY_FAVORITES_ANNONCEMENTS_LIST_FAILURE =
  "FETCH_MY_FAVORITES_ANNONCEMENTS_LIST_FAILURE";

export const ADD_FAVORITE_ANNONCEMENT_SUCCESS =
  "ADD_FAVORITE_ANNONCEMENT_SUCCESS";
export const ADD_FAVORITE_ANNONCEMENT_FAILURE =
  "ADD_FAVORITE_ANNONCEMENT_FAILURE";

export const DELETE_FAVORITE_ANNONCEMENT_SUCCESS =
  "DELETE_FAVORITE_ANNONCEMENT_SUCCESS";
export const DELETE_FAVORITE_ANNONCEMENT_FAILURE =
  "DELETE_FAVORITE_ANNONCEMENT_FAILURE";

export const EDIT_ANNONCEMENT_SITUATION_SUCCESS =
  "EDIT_ANNONCEMENT_SITUATION_SUCCESS";
export const EDIT_ANNONCEMENT_SITUATION_FAILED =
  "EDIT_ANNONCEMENT_SITUATION_FAILED";
